### ISSUE TITLE
Facing issue Something went wrong.

### ISSUE THREAD

**Issue by rajeshjadidminc** [Mastercard/commerce-web-android#7]
Hi,

I have integrated the lib(CommerceWebSdk) as you suggested, but facing the issue of "Something went wrong error" in the stage/prod URL environment.

![Screenshot_20221010_223306](https://user-images.githubusercontent.com/95206513/194918539-1f526dff-30dc-468e-b4a7-99a5a9abbcfc.png)

Below is the code snippet.

`
        val locale = Locale.US
        val checkoutId = "5tuEqCZoA_RE8Lqr4L0ubIrMvfoFNrhAFvET5ons948e6fe9"
        val checkoutUrl = "https://sandbox.src.mastercard.com/srci/"
        val allowedCardTypes: MutableSet<CardType> = HashSet()
        allowedCardTypes.add(CardType.MASTER)
        allowedCardTypes.add(CardType.VISA)
        allowedCardTypes.add(CardType.AMEX)

        val commerceConfig = CommerceConfig(locale, checkoutId, checkoutUrl, allowedCardTypes)
        CommerceWebSdk.getInstance().initialize(this,commerceConfig)
        var button = CommerceWebSdk.getInstance().getCheckoutButton(this);
        findViewById<LinearLayout>(R.id.lin).addView(button)
    }

    override fun setRequest(request: CheckoutRequest?) {
        Log.d("Raja", "onCreate: ${request.toString()}")
    }

    override fun getCheckoutRequest(listener: CheckoutRequestListener?) {
        listener?.setRequest(getSrcCheckoutRequest())
    }

    private fun getSrcCheckoutRequest(): CheckoutRequest? {
        val mastercardFormatSet: MutableSet<MastercardFormat> = HashSet()
        mastercardFormatSet.add(MastercardFormat.ICC)
        mastercardFormatSet.add(MastercardFormat.UCAF)

        val mastercard: CryptoOptions = Mastercard(mastercardFormatSet)
        val cryptoOptionsSet: MutableSet<CryptoOptions> = HashSet()
        cryptoOptionsSet.add(mastercard)

        return CheckoutRequest.Builder()
            .amount(100.0)
            .cartId(UUID.randomUUID().toString())
            .currency("USD")
            .callbackUrl("intent://commerce/#Intent;scheme=mastercarddemo;package=com.test.mastercarddemo;end")
            .cryptoOptions(cryptoOptionsSet)
            .suppressShippingAddress(false)
            .build()
    }`

**Comment by kragavan** [comment]
Hi, Can you please let us know the following information:
1.  Your company/organization info?
2. How did you generate checkoutId? 

Thanks

**Comment by rajeshjadidminc** [comment]
Hi,

I have created the developer account and below is the detail:
Email Address:  rjadi@dminc.com
Name: Rajesh Jadi
Company Name:DMI
Company Type: Other
Country:India

And for checkout id i have used random string.

**Comment by kragavan** [comment]
> And for checkout id i have used random string.

This will not work. You have to use checkoutId provided to you while Merchant onboarding.
